#!/bin/bash
echo "Checking Gemini VS Code environment variables:"
echo "GEMINI_VSCODE_EXTENSION: $GEMINI_VSCODE_EXTENSION"
echo "GEMINI_VSCODE_EXTENSION_PATH: $GEMINI_VSCODE_EXTENSION_PATH"
echo "VSCODE_WORKSPACE_FOLDER: $VSCODE_WORKSPACE_FOLDER"